//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.12 at 01:34:32 PM PDT 
//


package com.tpo.movies;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tpo.movies package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Movie_QNAME = new QName("http://www.tpo.com/movies", "movie");
    private final static QName _Movies_QNAME = new QName("http://www.tpo.com/movies", "movies");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tpo.movies
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Movies }
     * 
     */
    public Movies createMovies() {
        return new Movies();
    }

    /**
     * Create an instance of {@link MovieType }
     * 
     */
    public MovieType createMovieType() {
        return new MovieType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MovieType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tpo.com/movies", name = "movie")
    public JAXBElement<MovieType> createMovie(MovieType value) {
        return new JAXBElement<MovieType>(_Movie_QNAME, MovieType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Movies }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tpo.com/movies", name = "movies")
    public JAXBElement<Movies> createMovies(Movies value) {
        return new JAXBElement<Movies>(_Movies_QNAME, Movies.class, null, value);
    }

}
